before:
  hooks:
    - go mod download
builds:
  - id: kubectl-flame
    main: ./cli/main.go
    binary: kubectl-flame
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      #- darwin
    goarch:
      - amd64
      - arm64
    ldflags: |
      -X github.com/simplexiengage/kubectl-flame/cli/cmd/version.semver={{ .Tag }}
      -X github.com/simplexiengage/kubectl-flame/cli/cmd/version.date={{ .Date }}
      -X github.com/simplexiengage/kubectl-flame/cli/cmd/version.commit={{ .Commit }}
archives:
  - id: kubectl-flame-archive
    name_template: |
      kubectl-flame_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
      {{- end -}}
    builds:
      - kubectl-flame
    files: ["LICENSE"]
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256